FROM node:18-alpine AS api
WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm ci

# Copy only server code
COPY server ./server
COPY src/utils ./src/utils

# Ensure users.json is included
COPY server/users.json ./server/users.json

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "server/index.js"]
